[package]
name = "aoc2024"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
phf = { version = "0.11.2", features = ["macros"] }
regex = "1.11.1"
